name: 💡 General Feature Request
description: Use this template for requesting new features
title: '[FEATURE] <description>'
labels: ['feature']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the enhancement you propose.,
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description:  What would be one or more things that this feature would require to work? If you don't know, that's fine! A maintainer can fill in the information or re-file the issue.
    validations:
      required: false
